"""BeiDou B1I D1 navigation message construction (BDS-SIS-ICD-2.0/2.1).

This module builds a standards-shaped B1I D1 bit stream from the BeiDou
ephemeris already parsed into :class:`gnss_sim.rinex.Ephemeris` so that a real
receiver can acquire the B1I code, synchronise on the 20-chip Neumann-Hoffman
(NH) secondary code, de-interleave, BCH-decode and finally compute a
position/clock solution.

Verified structure (cross-checked against two independent sources)
-------------------------------------------------------------------
.. [1] BDS-SIS-ICD-2.0/-2.1 (section 5.1.3 and 5.2.2).  Channel rate 50 bps,
   NH code ``00000100110101001110`` at 1 kbps (20 ms = one data bit), BCH
   ``g(X) = X**4 + X + 1`` (BCH(15,11,1)) plus a 30-bit block interleaver.
   Frame = 1500 bits / 30 s = 5 subframes; subframe = 300 bits / 6 s = 10
   words; word = 30 bits.  Word 1: 15 raw bits + one BCH block (26 info bits);
   words 2..10: two BCH blocks + interleaving (22 info bits each).
.. [2] Field bit positions/scale factors taken from GNSS-SDRLIB
   (``sdrnav_bds.c``, Taro Suzuki) and GNSS-SDR (``Beidou_DNAV.h``).  Both
   agree on every field used here (``toe``/``toc``, the Keplerian elements and
   the clock polynomial).  The two disagree on the number of bits read for
   ``TGD2`` (10 vs 6); TGD/ionosphere/UTC/almanac are **not** required for a
   position fix, so they are broadcast as zero rather than risking a wrong
   value.

Caveats (marked, not silently wrong)
------------------------------------
* The D1 field ordering/scale factors are taken from the two open-source
  decoders above; they were **not** verified against a live broadcast capture
  in this project.  :func:`self_test` verifies BCH, interleaving and a full
  subframe round-trip (build -> decode -> compare) but that only proves the
  encoder/decoder pair is self-consistent.
* ``TGD1/TGD2``, the BDS ionosphere ``alpha/beta`` and the UTC parameters are
  transmitted as zero (marked TODO).  They bias the clock by a few ns and do
  not prevent a first fix.
* The broadcast ``SOW`` follows the simulator's own time scale so that the
  receiver's ``t_k`` matches the geometry generated by
  :mod:`gnss_sim.engine` (see :func:`d1_frame_block`).

Bit polarity: the engine maps ``bit -> 1 - 2*bit`` (0 -> +1), consistent with
the other signals in this project; a receiver resolves the carrier phase.
"""

from __future__ import annotations

from typing import Sequence

import numpy as np

# ----------------------------------------------------------------------
# Format constants
# ----------------------------------------------------------------------
DATA_RATE_BPS = 50.0               # D1 channel rate
DATA_BIT_SECONDS = 0.02            # one D1 bit (50 bps)
NH_RATE_BPS = 1000.0               # secondary code rate
NH_CHIP_SECONDS = 0.001            # one NH chip (1 ms = one ranging-code period)
NH_LENGTH = 20
NH_CODE = np.array(
    [0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0],
    dtype=np.int8)

SUBFRAME_BITS = 300
SUBFRAME_SECONDS = 6
SUBFRAMES_PER_FRAME = 5
FRAME_BITS = SUBFRAME_BITS * SUBFRAMES_PER_FRAME       # 1500
FRAME_SECONDS = 30.0
WORDS_PER_SUBFRAME = 10
WORD_BITS = 30

PREAMBLE = "11100010010"             # 11-bit modified Barker code
PREAMBLE_BITS = np.array([int(c) for c in PREAMBLE], dtype=np.int8)
PREAMBLE_LENGTH = len(PREAMBLE)

BCH_N = 15
BCH_K = 11
BCH_PARITY = 4
#: g(X) = X**4 + X + 1 -> 0b10011
BCH_POLY = 0b10011

#: BDT reference constants (BDT = GPST - 14 s; BDT week = GPS week - 1356).
BDT_GPST_OFFSET_S = 14.0
BDT_WEEK_OFFSET = 1356


# ----------------------------------------------------------------------
# BCH(15,11,1) with g(X) = X**4 + X + 1
# ----------------------------------------------------------------------
def _poly_rem(bits: Sequence[int]) -> int:
    """Remainder of the polynomial ``bits`` (MSB first) divided by ``g(X)``."""
    reg = 0
    for b in bits:
        reg = (reg << 1) | (int(b) & 1)
        if reg & (1 << BCH_PARITY):        # degree >= 4
            reg ^= BCH_POLY
    return reg & 0xF


def bch_encode(info_bits: Sequence[int]) -> list[int]:
    """Systematic BCH(15,11,1) encode: 11 information + 4 parity bits."""
    info = [int(b) & 1 for b in info_bits]
    if len(info) != BCH_K:
        raise ValueError(f"BCH info must be {BCH_K} bits")
    reg = _poly_rem(info + [0] * BCH_PARITY)   # remainder of info(X)*X**4
    return info + [(reg >> (3 - i)) & 1 for i in range(BCH_PARITY)]


def _synonym_table() -> dict[int, int]:
    """Map a nonzero syndrome to the (0-based) bit position to flip.

    ``BCH(15,11)`` with a primitive generator is a Hamming code: each of the
    15 single-bit errors has a distinct syndrome.
    """
    def mul_x(r: int) -> int:
        r <<= 1
        if r & 0x10:
            r ^= BCH_POLY
        return r & 0xF

    table: dict[int, int] = {}
    rem = 1
    for exp in range(15):                  # rem = X**exp mod g(X)
        pos = 14 - exp                     # bit p has coefficient X**(14-p)
        table[rem] = pos
        rem = mul_x(rem)
    return table


_SYNDROME = _synonym_table()


def bch_decode(codeword: Sequence[int]) -> tuple[list[int], bool]:
    """Correct one bit of a 15-bit BCH codeword.

    Returns ``(corrected_bits, corrected)``; ``codeword`` is returned as a
    15-bit list (11 information + 4 parity) with the parity still appended.
    """
    cw = [int(b) & 1 for b in codeword]
    if len(cw) != BCH_N:
        raise ValueError(f"BCH codeword must be {BCH_N} bits")
    reg = _poly_rem(cw)
    if reg == 0:
        return cw, False
    pos = _SYNDROME.get(reg)
    if pos is None:                        # pragma: no cover - unreachable
        return cw, False
    cw[pos] ^= 1
    return cw, True


# ----------------------------------------------------------------------
# Interleaving of two 15-bit codewords into a 30-bit word
# ----------------------------------------------------------------------
def interleave(codeword1: Sequence[int], codeword2: Sequence[int]) -> list[int]:
    """Parallel/serial interleave: ``c1[0] c2[0] c1[1] c2[1] ...``."""
    c1 = [int(b) & 1 for b in codeword1]
    c2 = [int(b) & 1 for b in codeword2]
    if len(c1) != BCH_N or len(c2) != BCH_N:
        raise ValueError("each BCH codeword must be 15 bits")
    out: list[int] = []
    for i in range(BCH_N):
        out.append(c1[i])
        out.append(c2[i])
    return out


def deinterleave(word: Sequence[int]) -> tuple[list[int], list[int]]:
    """Inverse of :func:`interleave` (two 15-bit codewords)."""
    w = [int(b) & 1 for b in word]
    if len(w) != WORD_BITS:
        raise ValueError("word must be 30 bits")
    c1 = [w[2 * i] for i in range(BCH_N)]
    c2 = [w[2 * i + 1] for i in range(BCH_N)]
    return c1, c2


def encode_word(x1: Sequence[int], x2: Sequence[int]) -> list[int]:
    """Encode two 11-bit information blocks into a transmitted 30-bit word."""
    return interleave(bch_encode(x1), bch_encode(x2))


def decode_word(word: Sequence[int]) -> tuple[list[int], list[int]]:
    """Decode a transmitted word into ``(info22, parity8)``.

    ``info22`` is ``X1(11) + X2(11)`` and ``parity8`` is ``P1(4) + P2(4)``,
    i.e. the logical ("decoded") word layout used by the field positions.
    """
    c1, c2 = deinterleave(word)
    d1, _ = bch_decode(c1)
    d2, _ = bch_decode(c2)
    return d1[:BCH_K] + d2[:BCH_K], d1[BCH_K:] + d2[BCH_K:]


# ----------------------------------------------------------------------
# small bit helpers
# ----------------------------------------------------------------------
def _scale(value: float, lsb: float, width: int, signed: bool) -> int:
    raw = int(round(float(value) / lsb)) if lsb else int(round(float(value)))
    if signed:
        lo, hi = -(1 << (width - 1)), (1 << (width - 1)) - 1
    else:
        lo, hi = 0, (1 << width) - 1
    return max(lo, min(hi, raw))


def _put_parts(bits: list[int], parts: Sequence[tuple[int, int]],
               value: float, lsb: float = 1.0, signed: bool = False) -> None:
    """Write ``value`` MSB-first across the concatenated ``parts``."""
    width = sum(w for _pos, w in parts)
    raw = _scale(value, lsb, width, signed) & ((1 << width) - 1)
    chunk = [(raw >> (width - 1 - i)) & 1 for i in range(width)]
    k = 0
    for pos, w in parts:
        for j in range(w):
            bits[pos + j] = chunk[k]
            k += 1


def _put_raw_parts(bits: list[int], parts: Sequence[tuple[int, int]],
                   value: int, width: int | None = None) -> None:
    total = sum(w for _pos, w in parts)
    if width is None:
        width = total
    raw = int(value) & ((1 << width) - 1)
    chunk = [(raw >> (width - 1 - i)) & 1 for i in range(width)]
    k = 0
    for pos, w in parts:
        for j in range(w):
            bits[pos + j] = chunk[k]
            k += 1


def _read_parts(bits: Sequence[int], parts: Sequence[tuple[int, int]],
                signed: bool = False) -> int:
    width = sum(w for _pos, w in parts)
    value = 0
    for pos, w in parts:
        for j in range(w):
            value = (value << 1) | (int(bits[pos + j]) & 1)
    if signed and (value >> (width - 1)) & 1:
        value -= 1 << width
    return value


# ----------------------------------------------------------------------
# Subframe field layouts (0-based positions in the decoded 300-bit word)
# ----------------------------------------------------------------------
#: (parts, value, lsb, signed) with ``parts`` in transmitted (MSB-first) order.
_SF1_FIELDS = (
    ((42, 1), "svh", 1.0, False),
    ((43, 5), "aodc", 1.0, False),
    ((48, 4), "urai", 1.0, False),
    ((60, 13), "wn", 1.0, False),
    (((73, 9), (90, 8)), "toc_sec", 8.0, False),
    ((98, 10), "tgd1", 0.1e-9, True),
    (((108, 4), (120, 6)), "tgd2", 0.1e-9, True),
    ((126, 8), "alpha0", 2.0 ** -30, True),
    ((134, 8), "alpha1", 2.0 ** -27, True),
    ((150, 8), "alpha2", 2.0 ** -24, True),
    ((158, 8), "alpha3", 2.0 ** -24, True),
    (((166, 6), (180, 2)), "beta0", 2.0 ** 11, True),
    ((182, 8), "beta1", 2.0 ** 14, True),
    ((190, 8), "beta2", 2.0 ** 16, True),
    (((198, 4), (210, 4)), "beta3", 2.0 ** 16, True),
    ((214, 11), "af2", 2.0 ** -66, True),
    (((225, 7), (240, 17)), "af0", 2.0 ** -33, True),
    (((257, 5), (270, 17)), "af1", 2.0 ** -50, True),
    ((287, 5), "aode", 1.0, False),
)

_SF2_FIELDS = (
    (((42, 10), (60, 6)), "deltan", np.pi * 2.0 ** -43, True),
    (((66, 16), (90, 2)), "cuc", 2.0 ** -31, True),
    (((92, 20), (120, 12)), "m0", np.pi * 2.0 ** -31, True),
    (((132, 10), (150, 22)), "ecc", 2.0 ** -33, False),
    ((180, 18), "cus", 2.0 ** -31, True),
    (((198, 4), (210, 14)), "crc", 2.0 ** -6, True),
    (((224, 8), (240, 10)), "crs", 2.0 ** -6, True),
    (((250, 12), (270, 20)), "sqrta", 2.0 ** -19, False),
    ((290, 2), "toe_hi", 1.0, False),
)

_SF3_FIELDS = (
    (((42, 10), (60, 5)), "toe_lo", 1.0, False),
    (((65, 17), (90, 15)), "i0", np.pi * 2.0 ** -31, True),
    (((105, 7), (120, 11)), "cic", 2.0 ** -31, True),
    (((131, 11), (150, 13)), "omgdot", np.pi * 2.0 ** -43, True),
    (((163, 9), (180, 9)), "cis", 2.0 ** -31, True),
    (((189, 13), (210, 1)), "idot", np.pi * 2.0 ** -43, True),
    (((211, 21), (240, 11)), "omg0", np.pi * 2.0 ** -31, True),
    (((251, 11), (270, 21)), "aop", np.pi * 2.0 ** -31, True),
)

def _subframe_logical(sfid: int, sow: float, fields: Sequence) -> list[int]:
    """Build the decoded 300-bit layout for one subframe."""
    bits = [0] * SUBFRAME_BITS
    for i, b in enumerate(PREAMBLE_BITS):
        bits[i] = int(b)
    # bits 11..14 (1-based 12..15) are not decoded by the ICD field tables.
    _put_raw_parts(bits, ((15, 3),), sfid, 3)          # FraID
    _put_raw_parts(bits, ((18, 8), (30, 12)), int(round(sow)) % 604800, 20)
    for parts, name, lsb, signed in fields:
        if isinstance(parts[0], tuple):
            _put_parts(bits, parts, _field_value(name), lsb, signed)
        else:
            _put_parts(bits, (parts,), _field_value(name), lsb, signed)
    return bits


#: Filled by :func:`d1_subframe` for the current call (a tiny, single-threaded
#: callback so the field tables stay declarative).
_FIELD_VALUES: dict[str, float] = {}


def _field_value(name: str) -> float:
    return float(_FIELD_VALUES.get(name, 0.0))


def _encode_logical(logical: Sequence[int]) -> list[int]:
    """BCH-encode + interleave a decoded 300-bit subframe layout."""
    tx = list(logical[:30])
    info0 = logical[15:26]
    tx[26:30] = bch_encode(info0)[BCH_K:]
    for i in range(1, WORDS_PER_SUBFRAME):
        base = 30 * i
        x1 = logical[base:base + BCH_K]
        x2 = logical[base + BCH_K:base + 2 * BCH_K]
        tx.extend(interleave(bch_encode(x1), bch_encode(x2)))
    return tx


def _decode_logical(tx: Sequence[int]) -> list[int]:
    """Inverse of :func:`_encode_logical` (corrects a single bit per block)."""
    logical = list(tx[:30])
    cw0, _ = bch_decode(logical[15:30])
    logical[15:30] = cw0
    for i in range(1, WORDS_PER_SUBFRAME):
        info, parity = decode_word(tx[30 * i:30 * i + 30])
        logical.extend(info + parity)
    return logical


# ----------------------------------------------------------------------
# Subframe builders
# ----------------------------------------------------------------------
def d1_subframe(eph, sfid: int, sow_bdt: float, *, week: int | None = None,
                toe_sec: float | None = None, toc_sec: float | None = None,
                page: int = 1,
                alpha: Sequence[float] = (0.0, 0.0, 0.0, 0.0),
                beta: Sequence[float] = (0.0, 0.0, 0.0, 0.0)) -> list[int]:
    """Return one transmitted 300-bit D1 subframe for ``eph``.

    ``sow_bdt`` is the seconds-of-week at the leading edge of the preamble.
    ``week``/``toe_sec``/``toc_sec`` default to the (BDT) values parsed from
    the RINEX ephemeris.  TGD, ionosphere and UTC are broadcast as zero.
    """
    if sfid not in (1, 2, 3, 4, 5):
        raise ValueError("D1 subframe id must be 1..5")
    wk = int(eph.toe.week if week is None else week)
    toe = float(eph.toe.sec if toe_sec is None else toe_sec)
    toc = float(eph.toc.sec if toc_sec is None else toc_sec)
    toe_raw = int(round(toe / 8.0)) % (1 << 17)
    toc_raw = int(round(toc / 8.0)) % (1 << 17)

    _FIELD_VALUES.clear()
    _FIELD_VALUES.update({
        "svh": 0 if int(getattr(eph, "svhlth", 0)) == 0 else 1,
        "aodc": int(getattr(eph, "iodc", 0)) & 0x1F,
        "urai": int(getattr(eph, "ura", 0)) & 0xF,
        "wn": wk % (1 << 13),
        "toc_sec": toc,
        "tgd1": 0.0,
        "tgd2": 0.0,
        "alpha0": float(alpha[0]) if alpha else 0.0,
        "alpha1": float(alpha[1]) if alpha else 0.0,
        "alpha2": float(alpha[2]) if alpha else 0.0,
        "alpha3": float(alpha[3]) if alpha else 0.0,
        "beta0": float(beta[0]) if beta else 0.0,
        "beta1": float(beta[1]) if beta else 0.0,
        "beta2": float(beta[2]) if beta else 0.0,
        "beta3": float(beta[3]) if beta else 0.0,
        "af2": float(eph.af2),
        "af0": float(eph.af0),
        "af1": float(eph.af1),
        "aode": int(getattr(eph, "iode", 0)) & 0x1F,
        "deltan": float(eph.deltan),
        "cuc": float(eph.cuc),
        "m0": float(eph.m0),
        "ecc": float(eph.ecc),
        "cus": float(eph.cus),
        "crc": float(eph.crc),
        "crs": float(eph.crs),
        "sqrta": float(eph.sqrta),
        "toe_hi": (toe_raw >> 15) & 0x3,
        "toe_lo": toe_raw & 0x7FFF,
        "i0": float(eph.inc0),
        "cic": float(eph.cic),
        "omgdot": float(eph.omgdot),
        "cis": float(eph.cis),
        "idot": float(eph.idot),
        "omg0": float(eph.omg0),
        "aop": float(eph.aop),
    })
    if sfid == 1:
        logical = _subframe_logical(sfid, sow_bdt, _SF1_FIELDS)
    elif sfid == 2:
        logical = _subframe_logical(sfid, sow_bdt, _SF2_FIELDS)
    elif sfid == 3:
        logical = _subframe_logical(sfid, sow_bdt, _SF3_FIELDS)
    else:
        logical = [0] * SUBFRAME_BITS
        for i, b in enumerate(PREAMBLE_BITS):
            logical[i] = int(b)
        _put_raw_parts(logical, ((15, 3),), sfid, 3)
        _put_raw_parts(logical, ((18, 8), (30, 12)),
                       int(round(sow_bdt)) % 604800, 20)
        _put_raw_parts(logical, ((43, 7),), int(page) & 0x7F, 7)  # Pnum
    return _encode_logical(logical)


def d1_frame_block(eph, sow_start: float, *, week: int | None = None,
                   **kw) -> np.ndarray:
    """Return a 1500-bit (30 s) D1 frame as an ``int8`` 0/1 block.

    ``sow_start`` is the seconds-of-week at the leading edge of subframe 1.
    The five subframes advance ``sow_start`` by 6 s each.  ``sow_start`` should
    be the simulator's own seconds-of-week so the receiver's ``t_k`` matches
    the geometry produced by :class:`gnss_sim.engine.SignalEngine`.
    """
    parts = []
    for k, sfid in enumerate((1, 2, 3, 4, 5)):
        parts.append(np.array(
            d1_subframe(eph, sfid, (sow_start + 6.0 * k) % 604800.0,
                        week=week, page=1, **kw), dtype=np.int8))
    return np.concatenate(parts).astype(np.int8)


# ----------------------------------------------------------------------
# Decoding helpers (self-test / diagnostics)
# ----------------------------------------------------------------------
def parse_subframe(tx: Sequence[int]) -> dict:
    """Decode one transmitted 300-bit subframe into named fields."""
    if len(tx) != SUBFRAME_BITS:
        raise ValueError("subframe must be 300 bits")
    logical = _decode_logical(tx)
    out: dict[str, float | int] = {
        "subframe_id": _read_parts(logical, ((15, 3),)),
        "sow": _read_parts(logical, ((18, 8), (30, 12))),
        "preamble": "".join(str(int(b)) for b in logical[:PREAMBLE_LENGTH]),
    }
    for parts, name, lsb, signed in _SF1_FIELDS + _SF2_FIELDS + _SF3_FIELDS:
        if isinstance(parts[0], tuple):
            raw = _read_parts(logical, parts, signed)
        else:
            raw = _read_parts(logical, (parts,), signed)
        if name in ("svh", "aodc", "urai", "wn", "aode", "toe_hi", "toe_lo"):
            out[name] = raw
        else:
            out[name] = raw * lsb
    out["toe_raw"] = (int(out["toe_hi"]) << 15) | int(out["toe_lo"])
    out["toc_raw"] = _read_parts(logical, ((73, 9), (90, 8)))
    return out


# ----------------------------------------------------------------------
# self-test
# ----------------------------------------------------------------------
def self_test() -> None:
    """Verify BCH, interleaving and a full subframe round-trip."""
    # 1) NH code matches the ICD text.
    if NH_CODE.tolist() != [0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
                            0, 1, 1, 1, 0]:
        raise AssertionError("NH20 code mismatch")
    if PREAMBLE != "11100010010":
        raise AssertionError("D1 preamble mismatch")

    # 2) BCH: encode -> zero remainder; every single-bit error is corrected.
    rng = np.random.default_rng(20260925)
    for _ in range(64):
        info = [int(b) for b in rng.integers(0, 2, size=BCH_K)]
        cw = bch_encode(info)
        if _poly_rem(cw) != 0:
            raise AssertionError("BCH codeword has nonzero syndrome")
        for pos in range(BCH_N):
            bad = list(cw)
            bad[pos] ^= 1
            fixed, corrected = bch_decode(bad)
            if not corrected or fixed != cw:
                raise AssertionError(f"BCH failed to correct bit {pos}")

    # 3) Interleaver round-trip.
    for _ in range(16):
        c1 = [int(b) for b in rng.integers(0, 2, size=BCH_N)]
        c2 = [int(b) for b in rng.integers(0, 2, size=BCH_N)]
        d1, d2 = deinterleave(interleave(c1, c2))
        if d1 != c1 or d2 != c2:
            raise AssertionError("interleaver round-trip failed")

    # 4) Full subframe round-trip: build -> decode -> compare ephemeris.
    eph = _synthetic_ephemeris()
    pi = np.pi
    tol = {
        "deltan": pi * 2.0 ** -43, "cuc": 2.0 ** -31, "m0": pi * 2.0 ** -31,
        "ecc": 2.0 ** -33, "cus": 2.0 ** -31, "crc": 2.0 ** -6,
        "crs": 2.0 ** -6, "sqrta": 2.0 ** -19, "i0": pi * 2.0 ** -31,
        "cic": 2.0 ** -31, "omgdot": pi * 2.0 ** -43, "cis": 2.0 ** -31,
        "idot": pi * 2.0 ** -43, "omg0": pi * 2.0 ** -31,
        "aop": pi * 2.0 ** -31, "af0": 2.0 ** -33, "af1": 2.0 ** -50,
        "af2": 2.0 ** -66,
    }
    mapping = {
        1: {"af0": eph.af0, "af1": eph.af1, "af2": eph.af2,
            "toc_raw": round(eph.toc.sec / 8.0), "sow": 259200,
            "svh": 0, "aodc": eph.iodc, "urai": eph.ura, "wn": eph.toe.week,
            "aode": eph.iode},
        2: {"deltan": eph.deltan, "cuc": eph.cuc, "m0": eph.m0,
            "ecc": eph.ecc, "cus": eph.cus, "crc": eph.crc, "crs": eph.crs,
            "sqrta": eph.sqrta, "toe_hi": (round(eph.toe.sec / 8.0) >> 15) & 3},
        3: {"i0": eph.inc0, "cic": eph.cic, "omgdot": eph.omgdot,
            "cis": eph.cis, "idot": eph.idot, "omg0": eph.omg0,
            "aop": eph.aop, "toe_lo": round(eph.toe.sec / 8.0) & 0x7FFF},
    }
    raw_fields = {"toc_raw", "sow", "svh", "aodc", "urai", "wn", "aode",
                  "toe_raw", "toe_hi", "toe_lo"}
    for sfid in (1, 2, 3):
        tx = d1_subframe(eph, sfid, 259200.0)
        if len(tx) != SUBFRAME_BITS:
            raise AssertionError("subframe length")
        dec = parse_subframe(tx)
        if dec["subframe_id"] != sfid:
            raise AssertionError("subframe id round-trip")
        if dec["preamble"] != PREAMBLE:
            raise AssertionError("preamble round-trip")
        for name, want in mapping[sfid].items():
            got = float(dec[name])
            if name in raw_fields:
                if int(got) != int(want):
                    raise AssertionError(
                        f"subframe {sfid} field {name}: {got} != {want}")
            elif abs(got - float(want)) > tol[name]:
                raise AssertionError(
                    f"subframe {sfid} field {name}: {got} != {want}")
    sf2 = parse_subframe(d1_subframe(eph, 2, 259200.0))
    sf3 = parse_subframe(d1_subframe(eph, 3, 259200.0))
    toe_combined = (int(sf2["toe_hi"]) << 15) | int(sf3["toe_lo"])
    if toe_combined != int(round(eph.toe.sec / 8.0)):
        raise AssertionError("toe round-trip across subframes 2+3")

    # 5) Frame geometry: 1500 bits, 5 subframes, SOW advances by 6 s.
    frame = d1_frame_block(eph, 259200.0)
    if frame.shape != (FRAME_BITS,):
        raise AssertionError("D1 frame must be 1500 bits")
    if set(np.unique(frame).tolist()) != {0, 1}:
        raise AssertionError("D1 frame is not a 0/1 bit block")
    for k in range(SUBFRAMES_PER_FRAME):
        sub = parse_subframe(frame[300 * k:300 * (k + 1)])
        if sub["subframe_id"] != k + 1:
            raise AssertionError("frame subframe order")
        if sub["sow"] != int(259200 + 6 * k):
            raise AssertionError("frame SOW progression")


def _synthetic_ephemeris():
    from .gpstime import GpsTime
    from .rinex import Ephemeris

    eph = Ephemeris()
    eph.system = "C"
    eph.prn = 1
    eph.toe = GpsTime(1081, 259200.0)
    eph.toc = GpsTime(1081, 259200.0)
    eph.m0 = -0.948
    eph.deltan = 4.075e-9
    eph.ecc = 5.441e-4
    eph.sqrta = 6493.537
    eph.omg0 = -3.088
    eph.inc0 = 0.079969
    eph.aop = 0.247235
    eph.omgdot = -3.1162e-9
    eph.idot = 3.643e-10
    eph.cuc = 1.578e-5
    eph.cus = 1.102e-5
    eph.cic = -1.4575e-7
    eph.cis = -6.3795e-8
    eph.crc = -337.9375
    eph.crs = 476.71875
    eph.af0 = -7.6869e-7
    eph.af1 = 2.0428e-14
    eph.af2 = 0.0
    eph.tgd = 4.5e-9
    eph.iode = 1
    eph.iodc = 0
    eph.svhlth = 0
    eph.ura = 2
    return eph


if __name__ == "__main__":  # pragma: no cover
    self_test()
    print("beidou_nav self-test OK")
